# Generated by Django 5.1.3 on 2024-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
