# Generated by Django 5.1.3 on 2024-12-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='delete',
            new_name='paid',
        ),
    ]
