# Generated by Django 5.1.4 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_options_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='paid',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deleted_or_paid',
            field=models.BooleanField(default=False, verbose_name='Deleted or paid'),
        ),
    ]
