# Generated by Django 5.1 on 2024-11-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
