# Generated by Django 5.1.3 on 2024-12-08 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_options_alter_address_address_and_more'),
        ('carts', '0004_alter_cartitem_options_alter_promocode_options_and_more'),
        ('orders', '0003_order_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='alias',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='carts.cartitem', verbose_name='Cart Items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.promocode', verbose_name='Promo Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('SHIPPED', 'ارسال شده'), ('COMPLETED', 'تکمیل شده'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_delivery',
            field=models.BooleanField(default=False, verbose_name='Store Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
