# Generated by Django 5.1.4 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('COMPLETED', 'تکمیل شده'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=25, verbose_name='Status'),
        ),
    ]
