# Generated by Django 5.1 on 2024-11-15 07:13

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engine optimization.', max_length=800, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Description for search engines.', max_length=350, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medias.image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engine optimization.', max_length=800, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Description for search engines.', max_length=350, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('published_date', models.DateField(auto_now=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SIMPLE_PRODUCT', 'Simple Product'), ('VARIABLE_PRODUCT', 'Variable Product')], default='SIMPLE_PRODUCT', max_length=25)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], max_length=25, null=True)),
                ('discount_value', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_start_date', models.DateField(blank=True, null=True)),
                ('discount_end_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('related_to', models.ManyToManyField(blank=True, to='products.product')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medias.image')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('type', models.CharField(choices=[('LAYOUT', 'Layout'), ('SIZE', 'Size'), ('COLOR', 'Color')], default='COLOR', max_length=20)),
                ('variant_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medias.image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('track_inventory', models.BooleanField(default=True)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('variant_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medias.image')),
                ('variables', models.ManyToManyField(blank=True, to='products.variable')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
